AWS_REGION                  = "eu-west-1"
TWITTER_CONSUMER_KEY        = "change_me"
TWITTER_CONSUMER_SECRET     = "change_me"
TWITTER_ACCESS_TOKEN        = "change_me"
TWITTER_ACCESS_TOKEN_SECRET = "change_me"
bot_name                    = "my-bot-name"
